In [2]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV

https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)


In [3]:
#Importation des données
df=load_breast_cancer()
df

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [ ]:
print(df)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [6]:
#Variable cible
y=df.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [7]:
X=df.data
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
X.shape

(569, 30)

In [9]:
#Initiallisation de KNN avec ses hyperparamètre par défaut
knn=KNeighborsClassifier()

In [10]:
#5-fold cross-validation

In [11]:
cv_scores=cross_val_score(knn,X,y,cv=5,scoring='precision')

In [12]:
#Affichage des scores
print(cv_scores)

[0.8625     0.93243243 0.94520548 0.94594595 0.95652174]


In [13]:
#Score moyen arrondi à deux chiffres après la virgule
round(np.mean(cv_scores),2)

0.93

Grid Search

In [14]:
#Les hyperparamètres

In [17]:
#Affichage de knn
print(knn)

KNeighborsClassifier()


https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [18]:
#Dictionnaire des hyperparamètres avec leurs valeurs
grid={'n_neighbors':[1,3,5,7,9,10],
      'weights':['uniform','distance'],
      'algorithm':['auto','ball_tree','kd_tree','brute'],
      'metric':['euclidiean','manhattan'],
      'leaf_size':[10,20,30,40,50]
    
}

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [19]:
#Estimateur
model=GridSearchCV(estimator=KNeighborsClassifier(),param_grid=grid,scoring='precision',cv=5)

Le nombre de combinaison (nombre de modèle) avec nos hyperparamètre dans grid est 6*2*4*2*5=480. Et cv=5 modèles sont créé pour chaque combinaison. Alors le nombre total de modèle créé est :780*5=2400 modèles

In [20]:
#Recherche du meilleur modèle
model.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
1200 fits failed out of a total of 2400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
600 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py", line 198, in fit
    return self._fit(X, y)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_base.py", line 437, in _fit
    self._check_algorithm_metric()
  File "/usr/local/lib/python3.7/dist-packages/sklearn

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 20, 30, 40, 50],
                         'metric': ['euclidiean', 'manhattan'],
                         'n_neighbors': [1, 3, 5, 7, 9, 10],
                         'weights': ['uniform', 'distance']},
             scoring='precision')

In [21]:
model.cv_results_

{'mean_fit_time': array([0.0009985 , 0.00467834, 0.00074844, 0.0021729 , 0.00072179,
        0.00071592, 0.00070291, 0.00083175, 0.00216928, 0.0007792 ,
        0.00209713, 0.00068965, 0.00268707, 0.00201983, 0.00192962,
        0.00269747, 0.00092964, 0.00090327, 0.00091853, 0.00091124,
        0.00089469, 0.00090857, 0.00166373, 0.00083427, 0.00076036,
        0.00076995, 0.00074563, 0.00076551, 0.00077391, 0.00080271,
        0.00075359, 0.00071197, 0.00071473, 0.00068302, 0.00069752,
        0.00072575, 0.0008637 , 0.00091414, 0.00090728, 0.00085716,
        0.00087523, 0.00086288, 0.00209475, 0.00096436, 0.00097046,
        0.00088868, 0.00091748, 0.00096898, 0.00094228, 0.00083184,
        0.00098586, 0.00073819, 0.0007484 , 0.00070348, 0.00073838,
        0.00073814, 0.00073023, 0.00072241, 0.00075092, 0.00097146,
        0.00105968, 0.00087848, 0.00095539, 0.00085845, 0.00090861,
        0.00229588, 0.00127268, 0.00167942, 0.00100503, 0.00094023,
        0.00089793, 0.00083876,

In [22]:
#convertion du dictionnaire en une dataframe
results=pd.DataFrame(model.cv_results_)

In [23]:
#On s'interresse à 'params' et 'mean_test_score'
best=results[['params','mean_test_score']].sort_values(by='mean_test_score',ascending=False).head()
best

params  mean_test_score
70   {'algorithm': 'auto', 'leaf_size': 30, 'metric...         0.932089
46   {'algorithm': 'auto', 'leaf_size': 20, 'metric...         0.932089
94   {'algorithm': 'auto', 'leaf_size': 40, 'metric...         0.932089
454  {'algorithm': 'brute', 'leaf_size': 40, 'metri...         0.932089
214  {'algorithm': 'ball_tree', 'leaf_size': 40, 'm...         0.932089

In [24]:
#On remarque que les 5 meilleurs modèles ont le meme score avec des hyperparamètres différents

In [25]:
#Meilleur hyperparamétrage
best['params'].iloc[0]

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'manhattan',
 'n_neighbors': 10,
 'weights': 'uniform'}

In [26]:
#Meilleur score
best['mean_test_score'].iloc[0]

0.9320886591668218